services:
  postgres:
    image: postgres:16-alpine
    container_name: myapp_postgres
    command: postgres -p 5434
    ports:
      - '5434:5434'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
