export const REST_RESOURCE = {
  HEALTH: 'health',
  USERS: 'users',
  AUTH: 'auth',
  SIGNUP: 'signup',
  SIGNIN: 'signin',
  ME: 'me',
  ID: 'id',
  PROFILES: 'profiles',
  REQUEST: 'request',
  VERIFY: 'verify',
  COMPLETE: 'complete',
  PASSWORD_RESET: 'password-reset',
  GOOGLE: 'google',
};
